services:
  mysql:
    image: mysql:8.1
    container_name: ${MYSQL_CONTAINER_NAME:-saints-mysql}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-saintsdb}
      MYSQL_USER: ${MYSQL_USER:-saintsuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    restart: always

volumes:
  mysql_data:
