version: '3.9'
services:
  mysql:
    image: mysql:8.1
    container_name: saints-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'Password@1'
      MYSQL_DATABASE: 'saintsdb'
      MYSQL_USER: 'saintsuser'
      MYSQL_PASSWORD: 'Password@1'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    restart: always

volumes:
  mysql_data:
